---
title: "Egzamin z Wizualizacji Danych - Zestaw 1"
output:
  word_document: default
  pdf_document: default
header-includes: \usepackage[polish]{babel}
---

*Punktacja: maks. 60 pkt. 0-29 pkt - 2,0 (ndst). 30-38 pkt - 3,0 (dst). 39-44 pkt - 3,5 (dst+). 45-50 pkt - 4,0 (db). 51-53 pkt - 4,5 (db+), 54-60 pkt - 5,0 (bdb).*

Aby rozwiązanie było sprawdzane, kod musi w całości zostać poprawnie zinterpretowany. Kod powinien spełniać zasady stylu PEP8. Każde zadanie (numerowane) powinno być w oddzielnym pliku. Po zakończonej pracy wszystkie kody umieść w jednym folderze. Spakuj folder do jednego archiwum, nazwa archiwum to numer indeksu. Plik archiwum do sprawdzenia umieść na pulpicie.

Zad.1. (10 pkt) Napisz program, który oblicza pierwiastki wielomianu kwadratowego. Współczynniki wielomianu mają być pobrane ze standardowego wejścia (wpisane przez użytkownika). Obliczone pierwiastki mają być wyświetlone na standardowym wyjściu (konsoli).

Zad.2. (10 pkt) Stwórz klasę `Kolo` z jednym polem (zmienną) `promien`. Klasa powinna posiadać konstruktor ustawiający z argumentu pole `promien`. W klasie dodaj funkcję `pole` bez parametrów zwracającą pole koła. Stwórz przypadek testowy dla funkcji.

Zad.3. (10 pkt) Napisz funkcję, której argumentem jest string. Funkcja zwraca string powstały z odwrócenia kolejności znaków w argumencie funkcji. Stwórz przypadek testowy dla funkcji.

Zad.4. (15 pkt) W jednym pliku wykonaj poniższe czynności:

* załaduj dane z pliku `sport.csv` (zawarte są tam informacje popularności sportów w grupie nastolatków), upewnij się, że pierwszy wiersz nie jest ustawiony jako nagłówek.
* stwórz wykres kołowy prezentujący procentowe zainteresowanie poszczególnymi sportami. Każdy wycinek powinien być w innym kolorze i podpisany liczbą procentów (w zaokrągleniu do pełnych procentów) oraz nazwą sportu, którego dotyczy. Wykres powinien posiadać tytuł.
* na wykresie w lewym górnym rogu dodaj string ze swoim numerem indeksu.
* za pomocą kodu zapisz wykres w formacie pdf.

Inspirację do wykresu znajdziesz w pliku `zad4.png`.


Zad.5. (15 pkt) W jednym pliku wykonaj poniższe czynności:

* załaduj dane z pliku `wyksz.csv` jako ramkę danych,
* w ramki danych stwórz 3 oddzielne ramki danych zawierających odpowiednie wiersze zawierające dane o wykształceniu wyższym, średnim i podstawowym,
* wzorując się na pliku `zad5.png` stwórz wykres słupkowy prezentujący dane o wykształceniu względem przedziału wiekowego. Wykres powinien posiadać odpowiedni tytuł. Legenda powinna być umieszczona po prawej stronie w połowie wysokości. Etykiety i podziałki obu osi muszą być podpisane jak w pliku `zad5.png`.


Dane pochodzą z Narodowego Spisu Ludności z roku 2002. Źródło danych: Bank danych lokalnych GUS. 